/* automatically generated from lightdm-gtk-greeter.glade */
#ifdef __SUNPRO_C
#pragma align 4 (lightdm_gtk_greeter_ui)
#endif
#ifdef __GNUC__
static const char lightdm_gtk_greeter_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char lightdm_gtk_greeter_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><object class=\"Gt"
  "kWindow\" id=\"login_window\"><property name=\"name\">login_window</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"res"
  "izable\">False</property><property name=\"decorated\">False</property><"
  "child><object class=\"GtkTable\" id=\"table1\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">False</property><propert"
  "y name=\"border_width\">26</property><property name=\"n_rows\">5</prope"
  "rty><property name=\"n_columns\">2</property><property name=\"column_sp"
  "acing\">18</property><property name=\"row_spacing\">6</property><child>"
  "<object class=\"GtkComboBox\" id=\"user_combobox\"><property name=\"nam"
  "e\">user_combobox</property><property name=\"width_request\">200</prope"
  "rty><property name=\"can_focus\">True</property><property name=\"model\""
  ">user_liststore</property><signal name=\"changed\" handler=\"user_combo"
  "box_active_changed_cb\" swapped=\"no\"/><signal name=\"key-press-event\""
  " handler=\"user_combobox_key_press_cb\" swapped=\"no\"/></object><packi"
  "ng><property name=\"left_attach\">1</property><property name=\"right_at"
  "tach\">2</property><property name=\"y_options\"/></packing></child><chi"
  "ld><object class=\"GtkEntry\" id=\"password_entry\"><property name=\"na"
  "me\">prompt_entry</property><property name=\"width_request\">200</prope"
  "rty><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">True</property><property name=\"invisible_char\">\342\200\242</prop"
  "erty><property name=\"invisible_char_set\">True</property><property nam"
  "e=\"primary_icon_activatable\">False</property><property name=\"seconda"
  "ry_icon_activatable\">False</property><signal name=\"activate\" handler"
  "=\"login_cb\" swapped=\"no\"/></object><packing><property name=\"left_a"
  "ttach\">1</property><property name=\"right_attach\">2</property><proper"
  "ty name=\"top_attach\">2</property><property name=\"bottom_attach\">3</"
  "property><property name=\"y_options\"/></packing></child><child><object"
  " class=\"GtkImage\" id=\"user_image\"><property name=\"name\">user_imag"
  "e</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"pixel_size\">80</property>"
  "<property name=\"icon_name\">avatar-default</property></object><packing"
  "><property name=\"bottom_attach\">3</property><property name=\"x_option"
  "s\"/><property name=\"y_options\"/></packing></child><child><object cla"
  "ss=\"GtkHBox\" id=\"hbox2\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><child><object class=\"GtkB"
  "utton\" id=\"login_button\"><property name=\"name\">login_button</prope"
  "rty><property name=\"label\" translatable=\"yes\">Log In</property><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">True"
  "</property><property name=\"receives_default\">True</property><signal n"
  "ame=\"key-press-event\" handler=\"login_button_key_press_cb\" swapped=\""
  "no\"/><signal name=\"clicked\" handler=\"login_cb\" swapped=\"no\"/></o"
  "bject><packing><property name=\"expand\">False</property><property name"
  "=\"fill\">True</property><property name=\"pack_type\">end</property><pr"
  "operty name=\"position\">0</property></packing></child><child><object c"
  "lass=\"GtkButton\" id=\"cancel_button\"><property name=\"name\">cancel_"
  "button</property><property name=\"label\" translatable=\"yes\">Cancel</"
  "property><property name=\"visible\">True</property><property name=\"can"
  "_focus\">True</property><property name=\"receives_default\">True</prope"
  "rty><signal name=\"clicked\" handler=\"cancel_cb\" swapped=\"no\"/></ob"
  "ject><packing><property name=\"expand\">False</property><property name="
  "\"fill\">True</property><property name=\"position\">1</property></packi"
  "ng></child></object><packing><property name=\"left_attach\">1</property"
  "><property name=\"right_attach\">2</property><property name=\"top_attac"
  "h\">4</property><property name=\"bottom_attach\">5</property></packing>"
  "</child><child><object class=\"GtkEntry\" id=\"username_entry\"><proper"
  "ty name=\"name\">prompt_entry</property><property name=\"can_focus\">Tr"
  "ue</property><property name=\"no_show_all\">True</property><property na"
  "me=\"invisible_char\">\342\200\242</property><signal name=\"key-press-e"
  "vent\" handler=\"username_key_press_cb\" swapped=\"no\"/><signal name=\""
  "focus-out-event\" handler=\"username_focus_out_cb\" swapped=\"no\"/></o"
  "bject><packing><property name=\"left_attach\">1</property><property nam"
  "e=\"right_attach\">2</property><property name=\"top_attach\">1</propert"
  "y><property name=\"bottom_attach\">2</property></packing></child><child"
  "><object class=\"GtkAlignment\" id=\"infobar_compat\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "child><object class=\"GtkLabel\" id=\"message_label\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"label\" comments=\"This is a placeholder string and wil"
  "l be replaced with a message from PAM\">[message]</property></object></"
  "child></object><packing><property name=\"right_attach\">2</property><pr"
  "operty name=\"top_attach\">3</property><property name=\"bottom_attach\""
  ">4</property></packing></child><child><placeholder/></child></object></"
  "child></object><object class=\"GtkWindow\" id=\"panel_window\"><propert"
  "y name=\"name\">panel_window</property><property name=\"can_focus\">Fal"
  "se</property><property name=\"decorated\">False</property><child><objec"
  "t class=\"GtkHButtonBox\" id=\"buttonbox1\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><child><obj"
  "ect class=\"GtkLabel\" id=\"hostname_label\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"xalign\">0</property><property name=\"xpad\">6</property><proper"
  "ty name=\"label\">[hostname]</property></object><packing><property name"
  "=\"expand\">False</property><property name=\"fill\">True</property><pro"
  "perty name=\"position\">0</property></packing></child><child><object cl"
  "ass=\"GtkLabel\" id=\"clock_label\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"la"
  "bel\" translatable=\"yes\">label</property></object><packing><property "
  "name=\"expand\">False</property><property name=\"fill\">True</property>"
  "<property name=\"pack_type\">end</property><property name=\"position\">"
  "1</property></packing></child><child><object class=\"GtkMenuBar\" id=\""
  "menubar\"><property name=\"name\">menubar</property><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">True</property><pro"
  "perty name=\"take_focus\">True</property><property name=\"pack_directio"
  "n\">rtl</property><signal name=\"key-press-event\" handler=\"menubar_ke"
  "y_press_cb\" swapped=\"no\"/><child><object class=\"GtkMenuItem\" id=\""
  "power_menuitem\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">True</property><child type=\"submenu\"><object class=\""
  "GtkMenu\" id=\"power_menu\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><child><object class=\"GtkM"
  "enuItem\" id=\"suspend_menuitem\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"labe"
  "l\" translatable=\"yes\">Suspend</property><signal name=\"activate\" ha"
  "ndler=\"suspend_cb\" swapped=\"no\"/></object></child><child><object cl"
  "ass=\"GtkMenuItem\" id=\"hibernate_menuitem\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"label\" translatable=\"yes\">Hibernate</property><signal name=\""
  "activate\" handler=\"hibernate_cb\" swapped=\"no\"/></object></child><c"
  "hild><object class=\"GtkMenuItem\" id=\"restart_menuitem\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"label\" translatable=\"yes\">Restart...</property>"
  "<signal name=\"activate\" handler=\"restart_cb\" swapped=\"no\"/></obje"
  "ct></child><child><object class=\"GtkMenuItem\" id=\"shutdown_menuitem\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"label\" translatable=\"yes\">Shut Dow"
  "n...</property><signal name=\"activate\" handler=\"shutdown_cb\" swappe"
  "d=\"no\"/></object></child></object></child></object></child><child><ob"
  "ject class=\"GtkMenuItem\" id=\"a11y_menuitem\"><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">True</property><child t"
  "ype=\"submenu\"><object class=\"GtkMenu\" id=\"a11y_menu\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><child><object class=\"GtkCheckMenuItem\" id=\"large_font_menuitem\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"label\" translatable=\"yes\">Large Fo"
  "nt</property><signal name=\"toggled\" handler=\"a11y_font_cb\" swapped="
  "\"no\"/></object></child><child><object class=\"GtkCheckMenuItem\" id=\""
  "high_contrast_menuitem\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"label\" trans"
  "latable=\"yes\">High Contrast</property><signal name=\"toggled\" handle"
  "r=\"a11y_contrast_cb\" swapped=\"no\"/></object></child><child><object "
  "class=\"GtkCheckMenuItem\" id=\"keyboard_menuitem\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"label\" translatable=\"yes\">On Screen Keyboard</property"
  "><property name=\"use_underline\">True</property><signal name=\"toggled"
  "\" handler=\"a11y_keyboard_cb\" swapped=\"no\"/></object></child></obje"
  "ct></child></object></child><child><object class=\"GtkMenuItem\" id=\"l"
  "anguage_menuitem\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">True</property><child type=\"submenu\"><object class"
  "=\"GtkMenu\" id=\"language_menu\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property></object></child></ob"
  "ject></child><child><object class=\"GtkMenuItem\" id=\"session_menuitem"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">True</property><child type=\"submenu\"><object class=\"GtkMenu\" id="
  "\"session_menu\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">False</property></object></child></object></child></ob"
  "ject><packing><property name=\"expand\">False</property><property name="
  "\"fill\">True</property><property name=\"pack_type\">end</property><pro"
  "perty name=\"position\">2</property></packing></child></object></child>"
  "</object><object class=\"GtkListStore\" id=\"user_liststore\"><columns>"
  "<column type=\"gchararray\"/><column type=\"gchararray\"/><column type="
  "\"gint\"/></columns></object></interface>"
};

static const unsigned lightdm_gtk_greeter_ui_length = 10057u;

