/* automatically generated from lightdm-gtk-greeter.glade */
#ifdef __SUNPRO_C
#pragma align 4 (lightdm_gtk_greeter_ui)
#endif
#ifdef __GNUC__
static const char lightdm_gtk_greeter_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char lightdm_gtk_greeter_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><object class=\"Gt"
  "kAccelGroup\" id=\"a11y_accelgroup\"/><object class=\"GtkAccelGroup\" i"
  "d=\"power_accelgroup\"/><object class=\"GtkWindow\" id=\"login_window\""
  "><property name=\"name\">login_window</property><property name=\"can_fo"
  "cus\">False</property><property name=\"resizable\">False</property><pro"
  "perty name=\"decorated\">False</property><signal name=\"key-press-event"
  "\" handler=\"login_window_key_press_cb\" swapped=\"no\"/><accel-groups>"
  "<group name=\"a11y_accelgroup\"/><group name=\"power_accelgroup\"/></ac"
  "cel-groups><child><object class=\"GtkVBox\" id=\"vbox2\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">False</propert"
  "y><child><object class=\"GtkFrame\" id=\"content_frame\"><property name"
  "=\"name\">content_frame</property><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"labe"
  "l_xalign\">0</property><property name=\"shadow_type\">none</property><c"
  "hild><object class=\"GtkTable\" id=\"table1\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"margin_left\">24</property><property name=\"margin_right\">24</p"
  "roperty><property name=\"margin_top\">24</property><property name=\"n_r"
  "ows\">3</property><property name=\"n_columns\">2</property><property na"
  "me=\"column_spacing\">18</property><property name=\"row_spacing\">6</pr"
  "operty><child><object class=\"GtkComboBox\" id=\"user_combobox\"><prope"
  "rty name=\"name\">user_combobox</property><property name=\"width_reques"
  "t\">200</property><property name=\"can_focus\">False</property><propert"
  "y name=\"model\">user_liststore</property><signal name=\"changed\" hand"
  "ler=\"user_combobox_active_changed_cb\" swapped=\"no\"/></object><packi"
  "ng><property name=\"left_attach\">1</property><property name=\"right_at"
  "tach\">2</property><property name=\"y_options\"/></packing></child><chi"
  "ld><object class=\"GtkEntry\" id=\"password_entry\"><property name=\"na"
  "me\">prompt_entry</property><property name=\"width_request\">200</prope"
  "rty><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">True</property><property name=\"visibility\">False</property><prope"
  "rty name=\"invisible_char\">\342\200\242</property><property name=\"pri"
  "mary_icon_activatable\">False</property><property name=\"secondary_icon"
  "_activatable\">False</property><signal name=\"activate\" handler=\"logi"
  "n_cb\" swapped=\"no\"/><signal name=\"key-press-event\" handler=\"passw"
  "ord_key_press_cb\" swapped=\"no\"/></object><packing><property name=\"l"
  "eft_attach\">1</property><property name=\"right_attach\">2</property><p"
  "roperty name=\"top_attach\">2</property><property name=\"bottom_attach\""
  ">3</property><property name=\"y_options\"/></packing></child><child><ob"
  "ject class=\"GtkEntry\" id=\"username_entry\"><property name=\"name\">p"
  "rompt_entry</property><property name=\"can_focus\">True</property><prop"
  "erty name=\"no_show_all\">True</property><property name=\"invisible_cha"
  "r\">\342\200\242</property><signal name=\"focus-out-event\" handler=\"u"
  "sername_focus_out_cb\" swapped=\"no\"/><signal name=\"key-press-event\""
  " handler=\"username_key_press_cb\" swapped=\"no\"/></object><packing><p"
  "roperty name=\"left_attach\">1</property><property name=\"right_attach\""
  ">2</property><property name=\"top_attach\">1</property><property name=\""
  "bottom_attach\">2</property></packing></child><child><object class=\"Gt"
  "kFrame\" id=\"user_image_border\"><property name=\"name\">user_image_bo"
  "rder</property><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"label_xalign\">0</prope"
  "rty><property name=\"shadow_type\">none</property><child><object class="
  "\"GtkImage\" id=\"user_image\"><property name=\"name\">user_image</prop"
  "erty><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">False</property><property name=\"pixel_size\">80</property><proper"
  "ty name=\"icon_name\">avatar-default</property></object></child></objec"
  "t><packing><property name=\"bottom_attach\">3</property><property name="
  "\"x_options\"/><property name=\"y_options\"/></packing></child></object"
  "></child><child type=\"label_item\"><placeholder/></child></object><pac"
  "king><property name=\"expand\">True</property><property name=\"fill\">T"
  "rue</property><property name=\"position\">0</property></packing></child"
  "><child><object class=\"GtkAlignment\" id=\"infobar_compat\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><child><object class=\"GtkLabel\" id=\"message_label\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"label\" comments=\"This is a placeholder string "
  "and will be replaced with a message from PAM\">[message]</property></ob"
  "ject></child></object><packing><property name=\"expand\">True</property"
  "><property name=\"fill\">True</property><property name=\"position\">1</"
  "property></packing></child><child><object class=\"GtkFrame\" id=\"butto"
  "nbox_frame\"><property name=\"name\">buttonbox_frame</property><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"label_xalign\">0</property><property name=\"sh"
  "adow_type\">none</property><child><object class=\"GtkHBox\" id=\"hbox2\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"margin_left\">24</property><property "
  "name=\"margin_right\">24</property><property name=\"margin_bottom\">24<"
  "/property><child><object class=\"GtkButton\" id=\"login_button\"><prope"
  "rty name=\"label\" translatable=\"yes\">Log In</property><property name"
  "=\"name\">login_button</property><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">True</property><property name=\"receiv"
  "es_default\">True</property><signal name=\"clicked\" handler=\"login_cb"
  "\" swapped=\"no\"/></object><packing><property name=\"expand\">False</p"
  "roperty><property name=\"fill\">True</property><property name=\"pack_ty"
  "pe\">end</property><property name=\"position\">0</property></packing></"
  "child><child><object class=\"GtkButton\" id=\"cancel_button\"><property"
  " name=\"label\" translatable=\"yes\">Cancel</property><property name=\""
  "name\">cancel_button</property><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">True</property><property name=\"receives"
  "_default\">True</property><signal name=\"clicked\" handler=\"cancel_cb\""
  " swapped=\"no\"/></object><packing><property name=\"expand\">False</pro"
  "perty><property name=\"fill\">True</property><property name=\"position\""
  ">1</property></packing></child></object></child><child type=\"label_ite"
  "m\"><placeholder/></child></object><packing><property name=\"expand\">T"
  "rue</property><property name=\"fill\">True</property><property name=\"p"
  "osition\">2</property></packing></child></object></child></object><obje"
  "ct class=\"GtkWindow\" id=\"panel_window\"><property name=\"name\">pane"
  "l_window</property><property name=\"can_focus\">False</property><proper"
  "ty name=\"decorated\">False</property><accel-groups><group name=\"a11y_"
  "accelgroup\"/><group name=\"power_accelgroup\"/></accel-groups><child><"
  "object class=\"GtkHButtonBox\" id=\"buttonbox1\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">False</property><child"
  "><object class=\"GtkLabel\" id=\"hostname_label\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"xalign\">0</property><property name=\"xpad\">6</property><p"
  "roperty name=\"label\">[hostname]</property></object><packing><property"
  " name=\"expand\">False</property><property name=\"fill\">True</property"
  "><property name=\"position\">0</property></packing></child><child><obje"
  "ct class=\"GtkLabel\" id=\"clock_label\"><property name=\"visible\">Tru"
  "e</property><property name=\"can_focus\">False</property><property name"
  "=\"label\" translatable=\"yes\">label</property></object><packing><prop"
  "erty name=\"expand\">False</property><property name=\"fill\">True</prop"
  "erty><property name=\"pack_type\">end</property><property name=\"positi"
  "on\">1</property></packing></child><child><object class=\"GtkMenuBar\" "
  "id=\"menubar\"><property name=\"name\">menubar</property><property name"
  "=\"visible\">True</property><property name=\"can_focus\">True</property"
  "><property name=\"take_focus\">True</property><property name=\"pack_dir"
  "ection\">rtl</property><signal name=\"key-press-event\" handler=\"menub"
  "ar_key_press_cb\" swapped=\"no\"/><child><object class=\"GtkMenuItem\" "
  "id=\"power_menuitem\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">True</property><child type=\"submenu\"><object cl"
  "ass=\"GtkMenu\" id=\"power_menu\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"acce"
  "l_group\">power_accelgroup</property><child><object class=\"GtkMenuItem"
  "\" id=\"suspend_menuitem\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"label\" tra"
  "nslatable=\"yes\">Suspend</property><signal name=\"activate\" handler=\""
  "suspend_cb\" swapped=\"no\"/></object></child><child><object class=\"Gt"
  "kMenuItem\" id=\"hibernate_menuitem\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "label\" translatable=\"yes\">Hibernate</property><signal name=\"activat"
  "e\" handler=\"hibernate_cb\" swapped=\"no\"/></object></child><child><o"
  "bject class=\"GtkMenuItem\" id=\"restart_menuitem\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"label\" translatable=\"yes\">Restart...</property><signal"
  " name=\"activate\" handler=\"restart_cb\" swapped=\"no\"/></object></ch"
  "ild><child><object class=\"GtkMenuItem\" id=\"shutdown_menuitem\"><prop"
  "erty name=\"use_action_appearance\">False</property><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"accel_path\">&lt;Login&gt;/power/shutdown</property><prop"
  "erty name=\"label\" translatable=\"yes\">Shut Down...</property><signal"
  " name=\"activate\" handler=\"shutdown_cb\" swapped=\"no\"/></object></c"
  "hild></object></child></object></child><child><object class=\"GtkMenuIt"
  "em\" id=\"a11y_menuitem\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">True</property><child type=\"submenu\"><objec"
  "t class=\"GtkMenu\" id=\"a11y_menu\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"a"
  "ccel_group\">a11y_accelgroup</property><child><object class=\"GtkCheckM"
  "enuItem\" id=\"large_font_menuitem\"><property name=\"use_action_appear"
  "ance\">False</property><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">False</property><property name=\"accel_path\">&l"
  "t;Login&gt;/a11y/font</property><property name=\"label\" translatable=\""
  "yes\">Large Font</property><signal name=\"toggled\" handler=\"a11y_font"
  "_cb\" swapped=\"no\"/></object></child><child><object class=\"GtkCheckM"
  "enuItem\" id=\"high_contrast_menuitem\"><property name=\"use_action_app"
  "earance\">False</property><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"accel_path\""
  ">&lt;Login&gt;/a11y/contrast</property><property name=\"label\" transla"
  "table=\"yes\">High Contrast</property><signal name=\"toggled\" handler="
  "\"a11y_contrast_cb\" swapped=\"no\"/></object></child><child><object cl"
  "ass=\"GtkCheckMenuItem\" id=\"keyboard_menuitem\"><property name=\"use_"
  "action_appearance\">False</property><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"ac"
  "cel_path\">&lt;Login&gt;/a11y/keyboard</property><property name=\"label"
  "\" translatable=\"yes\">On Screen Keyboard</property><property name=\"u"
  "se_underline\">True</property><signal name=\"toggled\" handler=\"a11y_k"
  "eyboard_cb\" swapped=\"no\"/></object></child></object></child></object"
  "></child><child><object class=\"GtkMenuItem\" id=\"language_menuitem\">"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "True</property><property name=\"label\">language_code</property><child "
  "type=\"submenu\"><object class=\"GtkMenu\" id=\"language_menu\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">False</"
  "property></object></child></object></child><child><object class=\"GtkMe"
  "nuItem\" id=\"session_menuitem\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">True</property><child type=\"submenu\""
  "><object class=\"GtkMenu\" id=\"session_menu\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">False</property></object"
  "></child></object></child></object><packing><property name=\"expand\">F"
  "alse</property><property name=\"fill\">True</property><property name=\""
  "pack_type\">end</property><property name=\"position\">2</property></pac"
  "king></child></object></child></object><object class=\"GtkListStore\" i"
  "d=\"user_liststore\"><columns><column type=\"gchararray\"/><column type"
  "=\"gchararray\"/><column type=\"gint\"/></columns></object></interface>"
  ""
};

static const unsigned lightdm_gtk_greeter_ui_length = 12324u;

